# This is a config for E2B sandbox template.
# You can use template ID (8yn0aii31bapkinrarai) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("8yn0aii31bapkinrarai") # Sync sandbox
# sandbox = await AsyncSandbox.create("8yn0aii31bapkinrarai") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('8yn0aii31bapkinrarai')

team_id = "e9d536e4-41e3-486e-b77d-f0afa134f7fd"
start_cmd = "npm run dev"
dockerfile = "e2b.Dockerfile"
template_id = "8yn0aii31bapkinrarai"
